// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gram_matrix_cpp
arma::mat gram_matrix_cpp(const arma::mat& U, double h, const arma::Mat<int>& alphas, int n_total);
RcppExport SEXP _densityLP_gram_matrix_cpp(SEXP USEXP, SEXP hSEXP, SEXP alphasSEXP, SEXP n_totalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const arma::Mat<int>& >::type alphas(alphasSEXP);
    Rcpp::traits::input_parameter< int >::type n_total(n_totalSEXP);
    rcpp_result_gen = Rcpp::wrap(gram_matrix_cpp(U, h, alphas, n_total));
    return rcpp_result_gen;
END_RCPP
}
// lp_estimator_cpp
double lp_estimator_cpp(const arma::mat& U_quad, int n_total, const arma::mat& U_obs, double h, const arma::Mat<int>& alphas);
RcppExport SEXP _densityLP_lp_estimator_cpp(SEXP U_quadSEXP, SEXP n_totalSEXP, SEXP U_obsSEXP, SEXP hSEXP, SEXP alphasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U_quad(U_quadSEXP);
    Rcpp::traits::input_parameter< int >::type n_total(n_totalSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U_obs(U_obsSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const arma::Mat<int>& >::type alphas(alphasSEXP);
    rcpp_result_gen = Rcpp::wrap(lp_estimator_cpp(U_quad, n_total, U_obs, h, alphas));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_densityLP_gram_matrix_cpp", (DL_FUNC) &_densityLP_gram_matrix_cpp, 4},
    {"_densityLP_lp_estimator_cpp", (DL_FUNC) &_densityLP_lp_estimator_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_densityLP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
